/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/tmdb/import': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: operations['importTMDbData']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/tmdb/build-credits': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: operations['buildCredits']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/settings': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getAllSettings']
    put: operations['updateSettings']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/ratings': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: operations['getSeries']
    post?: never
    delete: operations['deleteRating']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/library/series/{id}/refresh': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: operations['refreshMediaItem']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/library/series/refresh': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: operations['refreshAllStaleItems']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/jellyfin/sync-profiles': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: operations['syncProfiles']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/jellyfin/sync-media': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: operations['syncMedia']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/sonarr/import': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['importSeries']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/ratings/import/imdb': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['importImdbCsv']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/radarr/refresh-ratings': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['refreshRatings']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/radarr/import': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['importMovies']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/profiles': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getAllProfiles']
    put?: never
    post: operations['createProfile']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/library/broken-media-items/seed': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['seed']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/agent/chat': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['chat']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/library/broken-media-items/{id}/resolve': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch: operations['resolveItem']
    trace?: never
  }
  '/api/v1/watch-activity': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getActivity']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/tmdb/test': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['testConnection']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/tmdb/series/{TMDbId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getShowDetails']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/tmdb/series/search': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['searchTVSeriesByName']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/tmdb/search': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['searchTMDbByName']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/tmdb/movies/{TMDbId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getMovieDetails']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/tmdb/movies/search': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['searchMoviesByName']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/test': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['test']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/sonarr/test': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['testConnection_1']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/settings/{key}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getSettingByKey']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/ratings/export': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['exportRatingsCsv']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/radarr/test': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['testConnection_2']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/radarr/movies': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['lookupMovieByTmdbId']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/profiles/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getProfileById']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/profiles/statistics': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getProfileStatistics']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/logs': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getLogs']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/library/series': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getSeries_1']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/library/series/watched/unrated': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getRecentlyWatchedUnratedSeries']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/library/series/broken': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getBrokenSeries']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/library/people': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getPeople']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/library/people/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getPersonById']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/library/movies': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getMovies']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/library/movies/watched/unrated': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getRecentlyWatchedUnratedMovies']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/library/movies/broken': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getBrokenMovies']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/library/genres': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getGenres']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/jobs': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getJobs']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/jobs/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getJob']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/jellyfin/test': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['testConnection_3']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/agent/suggestions': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getSuggestions']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/agent/prompt/{profileId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getPrompt']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/agent/conversation/{profileId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getConversation']
    put?: never
    post?: never
    delete: operations['clearConversation']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    ImportMediaItemRequestDTO: {
      id: string
      /** @enum {string} */
      mediaType?: 'MOVIE' | 'SERIES'
    }
    ImportMediaItemResponseDTO: {
      /** Format: uuid */
      id?: string
      title?: string
      TMDbId?: string
      /** @enum {string} */
      mediaType?: 'MOVIE' | 'SERIES'
    }
    GenericResponseDTO: {
      message?: string
      /** @enum {string} */
      status?:
        | '100 CONTINUE'
        | '101 SWITCHING_PROTOCOLS'
        | '102 PROCESSING'
        | '103 EARLY_HINTS'
        | '200 OK'
        | '201 CREATED'
        | '202 ACCEPTED'
        | '203 NON_AUTHORITATIVE_INFORMATION'
        | '204 NO_CONTENT'
        | '205 RESET_CONTENT'
        | '206 PARTIAL_CONTENT'
        | '207 MULTI_STATUS'
        | '208 ALREADY_REPORTED'
        | '226 IM_USED'
        | '300 MULTIPLE_CHOICES'
        | '301 MOVED_PERMANENTLY'
        | '302 FOUND'
        | '303 SEE_OTHER'
        | '304 NOT_MODIFIED'
        | '307 TEMPORARY_REDIRECT'
        | '308 PERMANENT_REDIRECT'
        | '400 BAD_REQUEST'
        | '401 UNAUTHORIZED'
        | '402 PAYMENT_REQUIRED'
        | '403 FORBIDDEN'
        | '404 NOT_FOUND'
        | '405 METHOD_NOT_ALLOWED'
        | '406 NOT_ACCEPTABLE'
        | '407 PROXY_AUTHENTICATION_REQUIRED'
        | '408 REQUEST_TIMEOUT'
        | '409 CONFLICT'
        | '410 GONE'
        | '411 LENGTH_REQUIRED'
        | '412 PRECONDITION_FAILED'
        | '413 CONTENT_TOO_LARGE'
        | '413 PAYLOAD_TOO_LARGE'
        | '414 URI_TOO_LONG'
        | '415 UNSUPPORTED_MEDIA_TYPE'
        | '416 REQUESTED_RANGE_NOT_SATISFIABLE'
        | '417 EXPECTATION_FAILED'
        | '418 I_AM_A_TEAPOT'
        | '421 MISDIRECTED_REQUEST'
        | '422 UNPROCESSABLE_CONTENT'
        | '422 UNPROCESSABLE_ENTITY'
        | '423 LOCKED'
        | '424 FAILED_DEPENDENCY'
        | '425 TOO_EARLY'
        | '426 UPGRADE_REQUIRED'
        | '428 PRECONDITION_REQUIRED'
        | '429 TOO_MANY_REQUESTS'
        | '431 REQUEST_HEADER_FIELDS_TOO_LARGE'
        | '451 UNAVAILABLE_FOR_LEGAL_REASONS'
        | '500 INTERNAL_SERVER_ERROR'
        | '501 NOT_IMPLEMENTED'
        | '502 BAD_GATEWAY'
        | '503 SERVICE_UNAVAILABLE'
        | '504 GATEWAY_TIMEOUT'
        | '505 HTTP_VERSION_NOT_SUPPORTED'
        | '506 VARIANT_ALSO_NEGOTIATES'
        | '507 INSUFFICIENT_STORAGE'
        | '508 LOOP_DETECTED'
        | '509 BANDWIDTH_LIMIT_EXCEEDED'
        | '510 NOT_EXTENDED'
        | '511 NETWORK_AUTHENTICATION_REQUIRED'
      data?: unknown
    }
    CreateSettingRequestDTO: {
      key: string
      value: string
      description?: string
    }
    CreateSettingsRequestDTO: {
      settings?: components['schemas']['CreateSettingRequestDTO'][]
    }
    SettingResponseDTO: {
      key?: string
      value?: string
      description?: string
    }
    SettingsWrapper: {
      settings?: components['schemas']['SettingResponseDTO'][]
    }
    RateRequestDTO: {
      /** Format: uuid */
      profileId: string
      /** Format: uuid */
      entityId: string
      /** @enum {string} */
      ratingMediaType: 'MEDIA_ITEM' | 'MEDIA_SEASON'
      /** Format: float */
      rating: number
    }
    PaginationMetadata: {
      /** Format: int32 */
      currentPage?: number
      /** Format: int32 */
      pageSize?: number
      /** Format: int64 */
      totalElements?: number
      /** Format: int32 */
      totalPages?: number
      isFirst?: boolean
      isLast?: boolean
      hasNext?: boolean
      hasPrevious?: boolean
    }
    ProfileResponseDTO: {
      /** Format: uuid */
      id?: string
      /** Format: date-time */
      createdAt?: string
      /** Format: date-time */
      updatedAt?: string
      name?: string
      jellyfinId?: string
    }
    ProfilesWrapper: {
      profiles?: components['schemas']['ProfileResponseDTO'][]
      pagination?: components['schemas']['PaginationMetadata']
    }
    BackgroundJobResponseDTO: {
      /** Format: uuid */
      id?: string
      /** @enum {string} */
      type?:
        | 'JELLYFIN_SYNC'
        | 'CSV_IMPORT'
        | 'RADARR_IMPORT'
        | 'RADARR_RATINGS_REFRESH'
        | 'SONARR_IMPORT'
      /** @enum {string} */
      status?: 'PENDING' | 'RUNNING' | 'COMPLETED' | 'FAILED'
      message?: string
      /** Format: uuid */
      profileId?: string
      /** Format: date-time */
      startedAt?: string
      /** Format: date-time */
      finishedAt?: string
      /** Format: date-time */
      createdAt?: string
      /** Format: date-time */
      updatedAt?: string
    }
    CreateProfileRequestDTO: {
      name: string
      jellyfinId?: string
    }
    ProfileWrapper: {
      profile?: components['schemas']['ProfileResponseDTO']
    }
    BrokenMediaItemResponseDTO: {
      /** Format: uuid */
      id?: string
      title?: string
      jellyfinId?: string
      TMDbId?: string
      IMDbId?: string
      /** Format: int32 */
      productionYear?: number
      missingFields?: string
      /** Format: uuid */
      resolvedMediaItemId?: string
      resolved?: boolean
    }
    AgentChatRequestDTO: {
      /** Format: uuid */
      profileId: string
      message: string
    }
    AgentChatResponseDTO: {
      reply?: string
      agent?: string
    }
    ResolveBrokenMediaItemRequestDTO: {
      /** Format: uuid */
      mediaItemId: string
    }
    WatchActivityFiltersDTO: {
      /** Format: uuid */
      profileId?: string
      startDate?: string
      endDate?: string
      /** @enum {string} */
      mediaType?: 'MOVIE' | 'SERIES'
      posterSize?: string
      backdropSize?: string
    }
    Pageable: {
      /** Format: int32 */
      page?: number
      /** Format: int32 */
      size?: number
      sort?: string[]
    }
    CastMemberResponseDTO: {
      /** Format: uuid */
      id?: string
      person?: components['schemas']['PersonResponseDTO']
      character?: string
      /** Format: int32 */
      order?: number
    }
    CrewMemberResponseDTO: {
      /** Format: uuid */
      id?: string
      person?: components['schemas']['PersonResponseDTO']
      job?: string
      department?: string
      profilePathUrl?: string
    }
    EpisodeResponseDTO: {
      /** Format: uuid */
      id?: string
      jellyfinId?: string
      /** Format: int32 */
      episode?: number
      title?: string
      /** Format: int32 */
      runtimeMinutes?: number
    }
    GenreResponseDTO: {
      /** Format: uuid */
      id?: string
      name?: string
    }
    MediaItemMetadataResponseDTO: {
      description?: string
      posterImageUrl?: string
      backdropImageUrl?: string
      /** Format: float */
      imdbRating?: number
      /** Format: int32 */
      rottenTomatoesRating?: number
    }
    MediaSeasonMetadataResponseDTO: {
      /** Format: int32 */
      episodeCount?: number
      posterImageUrl?: string
      airDate?: string
    }
    MovieResponseDTO: {
      /** Format: uuid */
      id?: string
      jellyfinId?: string
      title?: string
      TMDbId?: string
      IMDbId?: string
      /** Format: int32 */
      productionYear?: number
      /** Format: int32 */
      runtimeMinutes?: number
      metadata?: components['schemas']['MediaItemMetadataResponseDTO']
      genres?: components['schemas']['GenreResponseDTO'][]
      cast?: components['schemas']['CastMemberResponseDTO'][]
      crew?: components['schemas']['CrewMemberResponseDTO'][]
      /** Format: float */
      myRating?: number
    }
    PersonResponseDTO: {
      /** Format: uuid */
      id?: string
      name?: string
      TMDbId?: string
      profilePathUrl?: string
    }
    SeasonResponseDTO: {
      /** Format: uuid */
      id?: string
      jellyfinId?: string
      /** Format: int32 */
      season?: number
      title?: string
      metadata?: components['schemas']['MediaSeasonMetadataResponseDTO']
      episodes?: components['schemas']['EpisodeResponseDTO'][]
      /** Format: float */
      myRating?: number
    }
    ShowResponseDTO: {
      /** Format: uuid */
      id?: string
      jellyfinId?: string
      title?: string
      TMDbId?: string
      IMDbId?: string
      /** Format: int32 */
      productionYear?: number
      /** Format: int32 */
      runtimeMinutes?: number
      metadata?: components['schemas']['MediaItemMetadataResponseDTO']
      genres?: components['schemas']['GenreResponseDTO'][]
      seasons?: components['schemas']['SeasonResponseDTO'][]
      cast?: components['schemas']['CastMemberResponseDTO'][]
      crew?: components['schemas']['CrewMemberResponseDTO'][]
      /** Format: float */
      myRating?: number
    }
    WatchActivityWrapper: {
      events?: components['schemas']['WatchEventResponseDTO'][]
      pagination?: components['schemas']['PaginationMetadata']
    }
    WatchEventResponseDTO: {
      /** Format: uuid */
      id?: string
      /** Format: date-time */
      watchedAt?: string
      /** @enum {string} */
      eventType?: 'START' | 'PROGRESS' | 'COMPLETE'
      /** Format: int32 */
      positionSeconds?: number
      movie?: components['schemas']['MovieResponseDTO']
      show?: components['schemas']['ShowResponseDTO']
      /** Format: int32 */
      seasonNumber?: number
      /** Format: int32 */
      episodeNumber?: number
      episodeTitle?: string
    }
    TMDbCreditCastMemberResponseDTO: {
      name?: string
      character?: string
      profile_path?: string
      id?: string
      /** Format: int32 */
      order?: number
    }
    TMDbCreditCrewMemberResponseDTO: {
      name?: string
      department?: string
      job?: string
      profile_path?: string
      id?: string
    }
    TMDbCreditsResponseDTO: {
      cast?: components['schemas']['TMDbCreditCastMemberResponseDTO'][]
      crew?: components['schemas']['TMDbCreditCrewMemberResponseDTO'][]
    }
    TMDbEpisodeResponseDTO: {
      /** Format: int32 */
      id?: number
      name?: string
      overview?: string
      /** Format: int32 */
      episode_number?: number
      /** Format: int32 */
      season_number?: number
      air_date?: string
      /** Format: int32 */
      runtime?: number
      still_path?: string
      /** Format: double */
      vote_average?: number
      /** Format: int32 */
      vote_count?: number
    }
    TMDbGenreResponseDTO: {
      /** Format: int32 */
      id?: number
      name?: string
    }
    TMDbSeasonResponseDTO: {
      /** Format: int32 */
      episode_count?: number
      poster_path?: string
      air_date?: string
      /** Format: int32 */
      season_number?: number
      name?: string
    }
    TMDbSeasonWithEpisodesResponseDTO: {
      _id?: string
      name?: string
      overview?: string
      poster_path?: string
      air_date?: string
      /** Format: int32 */
      season_number?: number
      /** Format: double */
      vote_average?: number
      episodes?: components['schemas']['TMDbEpisodeResponseDTO'][]
    }
    TMDbShowFullDetailsResponseDTO: {
      /** Format: int32 */
      id?: number
      overview?: string
      poster_path?: string
      backdrop_path?: string
      seasons?: components['schemas']['TMDbSeasonResponseDTO'][]
      credits?: components['schemas']['TMDbCreditsResponseDTO']
      homepage?: string
      name?: string
      original_name?: string
      original_language?: string
      status?: string
      imdb_id?: string
      genres?: components['schemas']['TMDbGenreResponseDTO'][]
      /** Format: int32 */
      number_of_episodes?: number
      /** Format: int32 */
      number_of_seasons?: number
      first_air_date?: string
      seasonDetails?: {
        [key: string]: unknown
      }
      episode_run_time?: number[]
      allSeasonDetails?: {
        [key: string]: components['schemas']['TMDbSeasonWithEpisodesResponseDTO']
      }
    }
    SearchFiltersDTO: {
      query: string
      posterSize?: string
      /** Format: int32 */
      page?: number
    }
    SearchTMDbResponseDTO: {
      /** Format: int32 */
      id?: number
      title?: string
      releaseDate?: string
      posterPath?: string
      backdropPath?: string
      description?: string
    }
    SearchTMDbWrapper: {
      results?: components['schemas']['SearchTMDbResponseDTO'][]
      /** Format: int32 */
      totalResults?: number
      /** Format: int32 */
      totalPages?: number
      /** Format: int32 */
      currentPage?: number
    }
    SearchGroupTMDbWrapper: {
      movies?: components['schemas']['SearchTMDbResponseDTO'][]
      series?: components['schemas']['SearchTMDbResponseDTO'][]
    }
    TMDbMovieFullDetailsResponseDTO: {
      /** Format: int32 */
      id?: number
      overview?: string
      poster_path?: string
      backdrop_path?: string
      credits?: components['schemas']['TMDbCreditsResponseDTO']
      homepage?: string
      title?: string
      original_title?: string
      original_language?: string
      status?: string
      imdb_id?: string
      genres?: components['schemas']['TMDbGenreResponseDTO'][]
      /** Format: int32 */
      runtime?: number
      release_date?: string
    }
    SettingWrapper: {
      setting?: components['schemas']['SettingResponseDTO']
    }
    RadarrMovieLookupResponseDTO: {
      title?: string
      /** Format: int32 */
      year?: number
      /** Format: int32 */
      tmdbId?: number
      imdbId?: string
      monitored?: boolean
      ratings?: components['schemas']['RadarrRatings']
    }
    RadarrRatingEntry: {
      /** Format: int32 */
      votes?: number
      /** Format: double */
      value?: number
      type?: string
    }
    RadarrRatings: {
      imdb?: components['schemas']['RadarrRatingEntry']
      rottenTomatoes?: components['schemas']['RadarrRatingEntry']
    }
    ProfilesFiltersDTO: {
      name: string
      /** Format: date-time */
      createdAtAfter?: string
      /** Format: date-time */
      createdAtBefore?: string
      /** Format: date-time */
      updatedAtAfter?: string
      /** Format: date-time */
      updatedAtBefore?: string
    }
    ProfileStatisticsRequestDTO: {
      /** Format: uuid */
      profileId: string
      /** Format: float */
      ratingThreshold?: number
      /** Format: int32 */
      minCount?: number
      /** Format: int32 */
      genresLimit?: number
      /** Format: int32 */
      actorsLimit?: number
      /** Format: int32 */
      directorsLimit?: number
      /** Format: int32 */
      producersLimit?: number
      /** Format: int32 */
      genreOverTimeLimit?: number
      profileImageSize?: string
    }
    DayOfWeekActivityDTO: {
      dayOfWeek?: string
      /** Format: int64 */
      count?: number
    }
    DecadeStatDTO: {
      /** Format: int32 */
      decade?: number
      /** Format: int64 */
      count?: number
      /** Format: double */
      averageRating?: number
    }
    GenreOverTimeYearDTO: {
      /** Format: int32 */
      year?: number
      genres?: components['schemas']['GenreYearStatDTO'][]
    }
    GenreStatDTO: {
      genreName?: string
      /** Format: int64 */
      count?: number
      /** Format: double */
      averageRating?: number
    }
    GenreYearStatDTO: {
      genreName?: string
      /** Format: int64 */
      count?: number
      /** Format: double */
      averageRating?: number
    }
    MediaTypeBreakdownDTO: {
      mediaType?: string
      /** Format: int64 */
      count?: number
      /** Format: int64 */
      totalCount?: number
      /** Format: double */
      percentage?: number
      /** Format: double */
      averageRating?: number
    }
    OverallStatsDTO: {
      /** Format: int64 */
      totalRatings?: number
      /** Format: int64 */
      totalItems?: number
      /** Format: double */
      averageRating?: number
      /** Format: float */
      minRating?: number
      /** Format: float */
      maxRating?: number
    }
    PersonStatDTO: {
      /** Format: uuid */
      personId?: string
      name?: string
      profilePathUrl?: string
      /** Format: double */
      averageRating?: number
      /** Format: int64 */
      itemCount?: number
    }
    ProfileStatisticsResponseDTO: {
      overallStats?: components['schemas']['OverallStatsDTO']
      ratingDistribution?: components['schemas']['RatingDistributionDTO'][]
      ratingDistributionByInteger?: components['schemas']['RatingDistributionDTO'][]
      mediaTypeBreakdown?: components['schemas']['MediaTypeBreakdownDTO'][]
      jellyfinMediaTypeBreakdown?: components['schemas']['MediaTypeBreakdownDTO'][]
      topGenresByCount?: components['schemas']['GenreStatDTO'][]
      topGenresByScore?: components['schemas']['GenreStatDTO'][]
      jellyfinTopGenresByCount?: components['schemas']['GenreStatDTO'][]
      jellyfinTopGenresByScore?: components['schemas']['GenreStatDTO'][]
      directorsByCount?: components['schemas']['PersonStatDTO'][]
      directorsByScore?: components['schemas']['PersonStatDTO'][]
      producersByCount?: components['schemas']['PersonStatDTO'][]
      producersByScore?: components['schemas']['PersonStatDTO'][]
      actorsByCount?: components['schemas']['PersonStatDTO'][]
      actorsByScore?: components['schemas']['PersonStatDTO'][]
      decadePreferences?: components['schemas']['DecadeStatDTO'][]
      jellyfinDecadePreferences?: components['schemas']['DecadeStatDTO'][]
      recentTrends?: components['schemas']['RecentTrendsDTO'][]
      jellyfinRecentTrends?: components['schemas']['RecentTrendsDTO'][]
      monthlyActivity?: components['schemas']['RatingActivityDTO'][]
      runtimeStats?: components['schemas']['RuntimeStatsDTO']
      jellyfinRuntimeStats?: components['schemas']['RuntimeStatsDTO']
      ratingConsistency?: components['schemas']['RatingConsistencyDTO']
      dayOfWeekActivity?: components['schemas']['DayOfWeekActivityDTO'][]
      jellyfinDayOfWeekActivity?: components['schemas']['DayOfWeekActivityDTO'][]
      ratingHeatmap?: components['schemas']['RatingHeatmapYearDTO'][]
      uniqueMediaPlayedHeatmap?: components['schemas']['RatingHeatmapYearDTO'][]
      genreOverTime?: components['schemas']['GenreOverTimeYearDTO'][]
      jellyfinGenreOverTime?: components['schemas']['GenreOverTimeYearDTO'][]
    }
    ProfileStatisticsWrapper: {
      statistics?: components['schemas']['ProfileStatisticsResponseDTO']
    }
    RatingActivityDTO: {
      period?: string
      /** Format: int64 */
      count?: number
      /** Format: double */
      averageRating?: number
    }
    RatingConsistencyDTO: {
      /** Format: double */
      standardDeviation?: number
      /** Format: double */
      variance?: number
      consistencyLevel?: string
    }
    RatingDistributionDTO: {
      range?: string
      /** Format: int64 */
      count?: number
      /** Format: double */
      percentage?: number
    }
    RatingHeatmapDayDTO: {
      date?: string
      /** Format: int64 */
      count?: number
    }
    RatingHeatmapYearDTO: {
      /** Format: int32 */
      year?: number
      days?: components['schemas']['RatingHeatmapDayDTO'][]
    }
    RecentTrendsDTO: {
      period?: string
      /** Format: int64 */
      count?: number
      /** Format: double */
      averageRating?: number
    }
    RuntimeStatsDTO: {
      /** Format: int32 */
      averageRuntime?: number
      /** Format: int64 */
      totalRuntime?: number
      /** Format: int32 */
      longestRuntime?: number
      /** Format: int32 */
      shortestRuntime?: number
    }
    LogEvent: {
      /** Format: int64 */
      timestamp?: number
      level?: string
      logger?: string
      message?: string
      mdc?: {
        [key: string]: string
      }
      serviceName?: string
    }
    LogsResponseWrapper: {
      logs?: components['schemas']['LogEvent'][]
      pagination?: components['schemas']['PaginationMetadata']
    }
    SeriesFiltersDTO: {
      /** Format: uuid */
      id?: string
      title: string
      /** Format: int32 */
      releasedAfter?: number
      /** Format: int32 */
      releasedBefore?: number
      genres?: string[]
      withSeasons?: boolean
      withEpisodes?: boolean
      posterSize?: string
      backdropSize?: string
      profileSize?: string
      /** Format: uuid */
      profileId?: string
      /** Format: float */
      ratingMin?: number
      /** Format: float */
      ratingMax?: number
      /** Format: uuid */
      personId?: string
      unrated?: boolean
    }
    SeriesResponseWrapper: {
      series?: components['schemas']['ShowResponseDTO'][]
      pagination?: components['schemas']['PaginationMetadata']
    }
    BrokenMediaItemResponseWrapper: {
      movies?: components['schemas']['BrokenMediaItemResponseDTO'][]
      pagination?: components['schemas']['PaginationMetadata']
    }
    PeopleFiltersDTO: {
      name: string
      profileSize?: string
    }
    PeopleWrapper: {
      people?: components['schemas']['PersonResponseDTO'][]
      pagination?: components['schemas']['PaginationMetadata']
    }
    MoviesFiltersDTO: {
      /** Format: uuid */
      id?: string
      title: string
      /** Format: int32 */
      releasedAfter?: number
      /** Format: int32 */
      releasedBefore?: number
      genres?: string[]
      posterSize?: string
      backdropSize?: string
      profileSize?: string
      /** Format: uuid */
      profileId?: string
      /** Format: float */
      ratingMin?: number
      /** Format: float */
      ratingMax?: number
      /** Format: uuid */
      personId?: string
      unrated?: boolean
    }
    MoviesResponseWrapper: {
      movies?: components['schemas']['MovieResponseDTO'][]
      pagination?: components['schemas']['PaginationMetadata']
    }
    GenresFiltersDTO: {
      name: string
    }
    GenresWrapper: {
      genres?: components['schemas']['GenreResponseDTO'][]
      pagination?: components['schemas']['PaginationMetadata']
    }
    BackgroundJobsWrapper: {
      jobs?: components['schemas']['BackgroundJobResponseDTO'][]
      pagination?: components['schemas']['PaginationMetadata']
    }
    AgentSuggestionsResponseDTO: {
      suggestions?: string[]
    }
    AgentPromptResponseDTO: {
      prompt?: string
      agent?: string
    }
    AgentConversationMessageResponseDTO: {
      /** Format: uuid */
      id?: string
      /** @enum {string} */
      role?: 'USER' | 'ASSISTANT'
      content?: string
      /** Format: date-time */
      sentAt?: string
    }
    AgentConversationWrapper: {
      conversation?: components['schemas']['AgentConversationMessageResponseDTO'][]
    }
    DeleteRateRequestDTO: {
      /** Format: uuid */
      profileId: string
      /** Format: uuid */
      entityId: string
      /** @enum {string} */
      ratingMediaType: 'MEDIA_ITEM' | 'MEDIA_SEASON'
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  importTMDbData: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ImportMediaItemRequestDTO']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ImportMediaItemResponseDTO']
        }
      }
    }
  }
  buildCredits: {
    parameters: {
      query?: {
        forceRefresh?: boolean
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['GenericResponseDTO']
        }
      }
    }
  }
  getAllSettings: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['SettingsWrapper']
        }
      }
    }
  }
  updateSettings: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateSettingsRequestDTO']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['SettingsWrapper']
        }
      }
    }
  }
  getSeries: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RateRequestDTO']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['GenericResponseDTO']
        }
      }
    }
  }
  deleteRating: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['DeleteRateRequestDTO']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['GenericResponseDTO']
        }
      }
    }
  }
  refreshMediaItem: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['GenericResponseDTO']
        }
      }
    }
  }
  refreshAllStaleItems: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['GenericResponseDTO']
        }
      }
    }
  }
  syncProfiles: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ProfilesWrapper']
        }
      }
    }
  }
  syncMedia: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Accepted */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['BackgroundJobResponseDTO']
        }
      }
    }
  }
  importSeries: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Accepted */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['BackgroundJobResponseDTO']
        }
      }
    }
  }
  importImdbCsv: {
    parameters: {
      query: {
        profileId: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: {
      content: {
        'application/json': {
          /** Format: binary */
          file: string
        }
      }
    }
    responses: {
      /** @description Accepted */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['BackgroundJobResponseDTO']
        }
      }
    }
  }
  refreshRatings: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Accepted */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['BackgroundJobResponseDTO']
        }
      }
    }
  }
  importMovies: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Accepted */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['BackgroundJobResponseDTO']
        }
      }
    }
  }
  getAllProfiles: {
    parameters: {
      query: {
        pageable: components['schemas']['Pageable']
        filters: components['schemas']['ProfilesFiltersDTO']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ProfilesWrapper']
        }
      }
    }
  }
  createProfile: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateProfileRequestDTO']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ProfileWrapper']
        }
      }
    }
  }
  seed: {
    parameters: {
      query?: {
        count?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['BrokenMediaItemResponseDTO'][]
        }
      }
    }
  }
  chat: {
    parameters: {
      query?: {
        agent?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AgentChatRequestDTO']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['AgentChatResponseDTO']
        }
      }
    }
  }
  resolveItem: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ResolveBrokenMediaItemRequestDTO']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['BrokenMediaItemResponseDTO']
        }
      }
    }
  }
  getActivity: {
    parameters: {
      query: {
        filters: components['schemas']['WatchActivityFiltersDTO']
        pageable: components['schemas']['Pageable']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['WatchActivityWrapper']
        }
      }
    }
  }
  testConnection: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['GenericResponseDTO']
        }
      }
    }
  }
  getShowDetails: {
    parameters: {
      query?: never
      header?: never
      path: {
        TMDbId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['TMDbShowFullDetailsResponseDTO']
        }
      }
    }
  }
  searchTVSeriesByName: {
    parameters: {
      query: {
        filters: components['schemas']['SearchFiltersDTO']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['SearchTMDbWrapper']
        }
      }
    }
  }
  searchTMDbByName: {
    parameters: {
      query: {
        filters: components['schemas']['SearchFiltersDTO']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['SearchGroupTMDbWrapper']
        }
      }
    }
  }
  getMovieDetails: {
    parameters: {
      query?: never
      header?: never
      path: {
        TMDbId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['TMDbMovieFullDetailsResponseDTO']
        }
      }
    }
  }
  searchMoviesByName: {
    parameters: {
      query: {
        filters: components['schemas']['SearchFiltersDTO']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['SearchTMDbWrapper']
        }
      }
    }
  }
  test: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': Record<string, never>
        }
      }
    }
  }
  testConnection_1: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['GenericResponseDTO']
        }
      }
    }
  }
  getSettingByKey: {
    parameters: {
      query?: never
      header?: never
      path: {
        key: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['SettingWrapper']
        }
      }
    }
  }
  exportRatingsCsv: {
    parameters: {
      query: {
        profileId: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'text/csv': string
        }
      }
    }
  }
  testConnection_2: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['GenericResponseDTO']
        }
      }
    }
  }
  lookupMovieByTmdbId: {
    parameters: {
      query: {
        tmdbId: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['RadarrMovieLookupResponseDTO']
        }
      }
    }
  }
  getProfileById: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ProfileWrapper']
        }
      }
    }
  }
  getProfileStatistics: {
    parameters: {
      query: {
        requestDTO: components['schemas']['ProfileStatisticsRequestDTO']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ProfileStatisticsWrapper']
        }
      }
    }
  }
  getLogs: {
    parameters: {
      query: {
        /** @description Filter by log level (DEBUG, INFO, WARN, ERROR) - case insensitive */
        level?: string
        /**
         * @description Start date-time in ISO-8601 format (e.g., '2024-02-14T10:30:00' or '2024-02-14T10:30:00Z')
         * @example 2024-02-14T10:30:00
         */
        startDate?: string
        /**
         * @description End date-time in ISO-8601 format (e.g., '2024-02-14T15:30:00' or '2024-02-14T15:30:00Z')
         * @example 2024-02-14T15:30:00
         */
        endDate?: string
        /** @description Filter by logger name (substring match, case insensitive) */
        logger?: string
        pageable: components['schemas']['Pageable']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['LogsResponseWrapper']
        }
      }
    }
  }
  getSeries_1: {
    parameters: {
      query: {
        pageable: components['schemas']['Pageable']
        filters: components['schemas']['SeriesFiltersDTO']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['SeriesResponseWrapper']
        }
      }
    }
  }
  getRecentlyWatchedUnratedSeries: {
    parameters: {
      query: {
        pageable: components['schemas']['Pageable']
        filters: components['schemas']['SeriesFiltersDTO']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['SeriesResponseWrapper']
        }
      }
    }
  }
  getBrokenSeries: {
    parameters: {
      query: {
        pageable: components['schemas']['Pageable']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['BrokenMediaItemResponseWrapper']
        }
      }
    }
  }
  getPeople: {
    parameters: {
      query: {
        pageable: components['schemas']['Pageable']
        filters: components['schemas']['PeopleFiltersDTO']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['PeopleWrapper']
        }
      }
    }
  }
  getPersonById: {
    parameters: {
      query?: {
        profileSize?: string
      }
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['PersonResponseDTO']
        }
      }
    }
  }
  getMovies: {
    parameters: {
      query: {
        pageable: components['schemas']['Pageable']
        filters: components['schemas']['MoviesFiltersDTO']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['MoviesResponseWrapper']
        }
      }
    }
  }
  getRecentlyWatchedUnratedMovies: {
    parameters: {
      query: {
        pageable: components['schemas']['Pageable']
        filters: components['schemas']['MoviesFiltersDTO']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['MoviesResponseWrapper']
        }
      }
    }
  }
  getBrokenMovies: {
    parameters: {
      query: {
        pageable: components['schemas']['Pageable']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['BrokenMediaItemResponseWrapper']
        }
      }
    }
  }
  getGenres: {
    parameters: {
      query: {
        pageable: components['schemas']['Pageable']
        filters: components['schemas']['GenresFiltersDTO']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['GenresWrapper']
        }
      }
    }
  }
  getJobs: {
    parameters: {
      query: {
        /** @description Filter by job type (JELLYFIN_SYNC, CSV_IMPORT) */
        type?:
          | 'JELLYFIN_SYNC'
          | 'CSV_IMPORT'
          | 'RADARR_IMPORT'
          | 'RADARR_RATINGS_REFRESH'
          | 'SONARR_IMPORT'
        /** @description Filter by job status (PENDING, RUNNING, COMPLETED, FAILED) */
        status?: 'PENDING' | 'RUNNING' | 'COMPLETED' | 'FAILED'
        /**
         * @description Start date-time in ISO-8601 format
         * @example 2024-02-14T10:30:00
         */
        startDate?: string
        /**
         * @description End date-time in ISO-8601 format
         * @example 2024-02-14T15:30:00
         */
        endDate?: string
        pageable: components['schemas']['Pageable']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['BackgroundJobsWrapper']
        }
      }
    }
  }
  getJob: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['BackgroundJobResponseDTO']
        }
      }
    }
  }
  testConnection_3: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['GenericResponseDTO']
        }
      }
    }
  }
  getSuggestions: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['AgentSuggestionsResponseDTO']
        }
      }
    }
  }
  getPrompt: {
    parameters: {
      query?: {
        agent?: string
      }
      header?: never
      path: {
        profileId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['AgentPromptResponseDTO']
        }
      }
    }
  }
  getConversation: {
    parameters: {
      query?: {
        agent?: string
      }
      header?: never
      path: {
        profileId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['AgentConversationWrapper']
        }
      }
    }
  }
  clearConversation: {
    parameters: {
      query?: {
        agent?: string
      }
      header?: never
      path: {
        profileId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
}
